In [3]:
import numpy as np
import pandas as pd
from scipy.linalg import eig

In [2]:
B=np.array([[2,2,4],[1,4,7],[2,5,4]])

In [4]:
evals, evacs=eig(B)

In [8]:
print(evals,"\n",evacs)

[10.93777843+0.j  1.25234419+0.j -2.19012261+0.j] 
 [[-0.42228933 -0.92515036 -0.29500861]
 [-0.67326244  0.37923364 -0.69446846]
 [-0.6069509  -0.01669331  0.65626479]]


In [9]:
evacs_reverse=np.linalg.inv(evacs)

In [10]:
print(evacs_reverse)

[[-0.24458613 -0.63090205 -0.77757728]
 [-0.88991249  0.47022663  0.09756081]
 [-0.24884369 -0.57153292  0.80710925]]


In [11]:
D=[[evals[0],0,0],[0,evals[1],0],[0,0,evals[2]]]

In [24]:
D

[[(10.937778429571388+0j), 0, 0],
 [0, (1.2523441851514185+0j), 0],
 [0, 0, (-2.1901226147228083+0j)]]

In [13]:
C=evacs@D@evacs_reverse

In [18]:
C.astype(float)

C:\Users\Y7000P\AppData\Local\Temp\ipykernel_21556\2108815929.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  C.astype(float)


array([[2., 2., 4.],
       [1., 4., 7.],
       [2., 5., 4.]])